spring:
  application:
    name: microservice-producer
    
server:
  port: 8002
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8007/eureka
      
      
  instance:
    hostname: localhost